### ISSUE TITLE
Github action triggered twice

### ISSUE THREAD

**Issue by ad1992** [amannn/action-semantic-pull-request#72] opened 2021-01-07 19:26 UTC
For some reason, this action gets triggered twice and I can see the same in the Pull requests i this repo as well.
Example https://github.com/amannn/action-semantic-pull-request/pull/71
<img width="807" alt="Screenshot 2021-01-08 at 12 53 48 AM" src="https://user-images.githubusercontent.com/11256141/103935209-3c8a6800-514c-11eb-894d-b76296204ab5.png">
@amannn any way to prevent this ?

**Comment by amannn** [comment] 2021-01-08 08:08
Hi @ad1992, thanks for the report. This seems to be a duplicate of https://github.com/amannn/action-semantic-pull-request/issues/27. The second check is necessary for the way the WIP feature is currently implemented.

I think the way forward is really to make the WIP feature opt-in, as usually you can use Github draft PRs for the same effect. Then the common case will only have one check. I'll look into this.

**Closed by amannn** 2021-01-08 08:08 UTC

**Comment by amannn** [comment] 2021-01-08 08:53
I've made the WIP feature which causes the second check now opt-in. Therefore the common case will only have a single check now.

Released in [3.0.0](https://github.com/amannn/action-semantic-pull-request/releases/tag/v3.0.0)

**Comment by ad1992** [comment] 2021-01-08 14:31
Thank you @amannn for the quick fix 👍 . Will check it

**Comment by amannn** [comment] 2021-01-08 14:34
Great! Just note that if you use `pull_request_target`, the latest version needs to be in the main branch before the change takes effect.

See also [the event triggers in the README](https://github.com/amannn/action-semantic-pull-request#event-triggers).

Btw. really cool to see that this action is used for excalidraw 🙂.

**Comment by ad1992** [comment] 2021-01-08 14:40
> Great! Just note that if you use pull_request_target, the latest version needs to be in the main branch before the change takes effect.

Thanks for pointing this out. Will try it out now :)

**Comment by ad1992** [comment] 2021-01-08 21:03
It works fine. Thank you for the quick fix 💯

**Comment by amannn** [comment] 2021-01-08 23:12
Great to hear! 🙂
