### ISSUE TITLE
[Request] Github Verified Action

### ISSUE THREAD

**Issue by douglasg14b** [amannn/action-semantic-pull-request#264] opened 2024-05-02 16:45 UTC
Can this action & publisher be verified by GitHub? I'm unsure how that process works though :/

![image](https://github.com/amannn/action-semantic-pull-request/assets/1400380/d1f73411-2c9f-486a-aab9-ba4d59fd3825)

In our org this is a requirement to use a GitHub action, which unfortunately means we cannot use this unless we fork it.

**Comment by amannn** [comment] 2024-05-03 07:15
This seems to be a duplicate of https://github.com/amannn/action-semantic-pull-request/issues/247.

**Closed by amannn** 2024-05-03 07:15 UTC
